name: Deploy to Hostinger

on:
  workflow_dispatch:
    inputs:
      run:
        description: 'Run deployment'
        required: true
        type: boolean
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME_PRODUCTION: ${{ secrets.DB_NAME_PRODUCTION }}
      DB_NAME_TEST: ${{ secrets.DB_NAME_TEST }}
    steps:
      - uses: actions/checkout@v5

      - name: Deploy to Hostinger
        uses: hostinger/deploy-on-vps@v2
        with:
          api-key: ${{ secrets.HOSTINGER_API_KEY }}
          virtual-machine: ${{ vars.HOSTINGER_VM_ID }}
          project-name: lisa
          personal-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          docker-compose-path: docker-compose.yml
          environment-variables: |
            RAILS_ENV=production
            RAILS_MASTER_KEY=${{ env.RAILS_MASTER_KEY }}
            DB_HOST=${{ env.DB_HOST }}
            DB_PORT=${{ env.DB_PORT }}
            DB_USERNAME=${{ env.DB_USERNAME }}
            DB_PASSWORD=${{ env.DB_PASSWORD }}
            DB_NAME_PRODUCTION=${{ env.DB_NAME_PRODUCTION }}
            DB_NAME_TEST=${{ env.DB_NAME_TEST }}
            SOLID_QUEUE_IN_PUMA=true
            SMTP_ADDRESS=${{ env.SMTP_ADDRESS }}
            SMTP_PORT=${{ env.SMTP_PORT }}
            SMTP_USERNAME=${{ env.SMTP_USERNAME }}
            SMTP_PASSWORD=${{ env.SMTP_PASSWORD }}
            SMTP_AUTH=${{ env.SMTP_AUTH }}
            MAILER_HOST=${{ env.MAILER_HOST }}
            MAILER_PORT=${{ env.MAILER_PORT }}
            MAIL_FROM=${{ env.MAIL_FROM }}
            LAB_NAME=${{ env.LAB_NAME }}
            OPENAI_KEY=${{ env.OPENAI_KEY }}
          cmd: |
            cd /root/lisa
            git pull origin master
            docker compose up -d --build
