name: Deploy to Hostinger

on:
  workflow_dispatch:
    inputs:
      run:
        description: 'Run deployment'
        required: true
        type: boolean
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME_PRODUCTION: ${{ secrets.DB_NAME_PRODUCTION }}
      DB_NAME_TEST: ${{ secrets.DB_NAME_TEST }}
    steps:
      - uses: actions/checkout@v6

      - name: Deploy to Hostinger
        uses: hostinger/deploy-on-vps@v2
        with:
          api-key: ${{ secrets.HOSTINGER_API_KEY }}
          virtual-machine: ${{ vars.HOSTINGER_VM_ID }}
          project-name: tbtb_dev_lis
          personal-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          docker-compose-path: docker-compose.yml
          environment-variables: |
            RAILS_ENV=production
            RAILS_MASTER_KEY=${{ env.RAILS_MASTER_KEY }}
            DB_HOST=${{ env.DB_HOST }}
            DB_PORT=${{ env.DB_PORT }}
            DB_USERNAME=${{ env.DB_USERNAME }}
            DB_PASSWORD=${{ env.DB_PASSWORD }}
            DB_NAME_PRODUCTION=${{ env.DB_NAME_PRODUCTION }}
            DB_NAME_TEST=${{ env.DB_NAME_TEST }}
            SOLID_QUEUE_IN_PUMA=true
